spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmvault
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
app:
  storage:
    location: uploads-prod